# Q1 Matrix multiplication Calculations

// "I'm still learning LaTeX and did my best, so I apologize if there are any errors or inconveniences."

The number of operations needed to perform matrix multiplication be
tween an (n, k )and a (k, m) matrix can be calculated as follows
:
Let matrix A be of size (n, k) and matrix B be of size (k, m).
For each element in the resulting matrix C of size (n, m), it requir'e'  k
multiplications 'and k' − 1 additi
ons.
So, for a single element Cij in the resulting matix: - Cki= ∑k(
p=1  Ai)  // it is summation where 'p' iterates from 1 to 'k' 

  Bpj
- This in'v'olves k multiplications (Aip × Bpj' ) an'  k − 1 addi't'ions (k p oducts
sum
med up).
For a (n, m) matrix C, t'here 'are n × m elements. Each element 'r'equires
k multiplica'tions' and k − 1 
additions.
Therefore, the total number of multiplications needed for thentire ma-
trix multip** lication  ** is
 n × m × k, and the total number of a** ddi ions is n ×
 **× (k − 1).
1


# Q2 Python code for Matrix multiplication

In [58]:
import numpy as np
import timeit

# List of lists matrix multiplication
def matrix_multiply_list_of_lists(A, B):
    rows_A = len(A)
    cols_A = len(A[0])
    rows_B = len(B)
    cols_B = len(B[0])

    if cols_A != rows_B:
        print("Matrices cannot be multiplied. Invalid dimensions.")
        return None

    result = [[0 for _ in range(cols_B)] for _ in range(rows_A)]

    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i][j] += A[i][k] * B[k][j]

    return result

# Example matrices as NumPy arrays
matrix_A = np.random.randint(1, 10, size=(100, 100))
matrix_B = np.random.randint(1, 10, size=(100, 100))

# Timing for list of lists matrix multiplication
time_list_of_lists = timeit.timeit(lambda: matrix_multiply_list_of_lists(matrix_A.tolist(), matrix_B.tolist()), number=10)

# Timing for NumPy matrix multiplication
time_numpy = timeit.timeit(lambda: np.dot(matrix_A, matrix_B), number=10)

print(f"Time taken for list of lists: {time_list_of_lists}")
print(f"Time taken for NumPy: {time_numpy}")

Time taken for list of lists: 3.340292600012617
Time taken for NumPy: 0.04256650002207607


NumPy is faster than list of lists. NumPy tends to be faster for matrix operations because it is implemented in optimized C and Fortran code, leveraging efficient algorithms and memory management. NumPy uses highly optimized libraries underneath, whereas the list of lists implementation is a pure Python solution, which tends to be slower for numerical computations due to Python's interpreted nature and lack of optimization for matrix operations.

# Q3 Median

In [61]:
def find_median_kth_smallest(arr):
    n = len(arr)
    
    # Function to find the kth smallest element using partitioning
    def kth_smallest(nums, k):
        left, right = 0, len(nums) - 1
        while left <= right:
            pivot_idx = partition(nums, left, right)
            if pivot_idx == k:
                return nums[pivot_idx]
            elif pivot_idx < k:
                left = pivot_idx + 1
            else:
                right = pivot_idx - 1

    # Helper function for partitioning
    def partition(nums, left, right):
        pivot = nums[right]
        i = left
        for j in range(left, right):
            if nums[j] <= pivot:
                nums[i], nums[j] = nums[j], nums[i]
                i += 1
        nums[i], nums[right] = nums[right], nums[i]
        return i

    # Calculate the index of the median
    if n % 2 == 1:
        return kth_smallest(arr, n // 2)
    else:
        left_median = kth_smallest(arr, n // 2 - 1)
        right_median = kth_smallest(arr, n // 2)
        return (left_median + right_median) / 2

import random

def quickselect_median(arr):
    def partition(arr, low, high):
        pivot = arr[high]
        i = low
        for j in range(low, high):
            if arr[j] <= pivot:
                arr[i], arr[j] = arr[j], arr[i]
                i += 1
        arr[i], arr[high] = arr[high], arr[i]
        return i

    def kth_smallest(arr, low, high, k):
        if low <= high:
            pivot_idx = partition(arr, low, high)
            if pivot_idx == k:
                return arr[pivot_idx]
            elif pivot_idx < k:
                return kth_smallest(arr, pivot_idx + 1, high, k)
            else:
                return kth_smallest(arr, low, pivot_idx - 1, k)
    
    n = len(arr)
    if n % 2 == 1:
        return kth_smallest(arr, 0, n - 1, n // 2)
    else:
        left_median = kth_smallest(arr, 0, n - 1, n // 2 - 1)
        right_median = kth_smallest(arr, 0, n - 1, n // 2)
        return (left_median + right_median) / 2



# Test array
test_array = np.random.rand(10000)


import time

# Time comparison
start_time = time.time()
median_kth_smallest = find_median_kth_smallest(test_array)
kth_smallest = time.time() - start_time

start_time = time.time()
median_quickselect = quickselect_median(test_array.copy())  # Make a copy to keep the original array intact
quickselect_time = time.time() - start_time

start_time = time.time()
median_numpy = np.median(test_array)
numpy_time = time.time() - start_time

# Print results
print("Median (Brute Force):", median_kth_smallest, "| Time:", kth_smallest)
print("Median (Quickselect):", median_quickselect, "| Time:", quickselect_time)
print("Median (NumPy):", median_numpy, "| Time:", numpy_time)

Median (Brute Force): 0.49950959351626467 | Time: 0.648468017578125
Median (Quickselect): 0.49950959351626467 | Time: 9.837093830108643
Median (NumPy): 0.49950959351626467 | Time: 0.0


# Q4 Gradient

// "I'm still learning LaTeX and did my best, so I apologize if there are any errors or inconveniences."

To find the gradient of the function f (x, y) = x^2 + y^3(sin(x)) with respect to 
x and y, we’ll need to compute the partial derivatives of f with respect to  
and y, respectivel
y.
Given:
f (x, y)^2  x2^3( y3 si)n(x)
Let’s find the partial derivat
ives:
1. Partial derivative with respect to/x ∂f
∂/ ):
∂/
∂x ^2 ∂
^∂( (x2 +) y3 sin(x))
Using the product rule and chain rule,/we get:
∂f^
(∂x = 2)
x2+ y3 cos(x)
2. Partial derivative with re/pect to / (∂f
/y ):
^
∂f
^∂( = ∂
)∂y (x2 + y3 sin(x))
Here, ^2 e derivative of x2 with respect to y is 0, an  t(e deri)vative of
y3 sin(x) with/respect^2(o y i))

So, the gradient of the function f (x, y) = x^2 + y^3 sin(x) with respect to x 
and y is the vector
:**
∇f (x, y) =(
2x ^3(y3 cos) (x),^2(y2 sin)(**)
2
s:
∂f
∂y = 3y2 sin(x

# Q5 JAX

In [62]:
pip install jax jaxlib

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [64]:
import jax
import jax.numpy as jnp

# Define the function
def f(x, y):
    return x**2 + y**3 * jnp.sin(x)

# Define a function that computes the gradient of f with respect to x and y
grad_f = jax.grad(f, argnums=(0, 1))

# Test with random values of x and y
x_values = jnp.array([1.5, 2.0, -0.5])  # Random x values
y_values = jnp.array([0.8, -1.2, 2.5])  # Random y values

# Compute gradients for each (x, y) pair
for x, y in zip(x_values, y_values):
    grad_x, grad_y = grad_f(x, y)
    analytical_grad_x = 2 * x + y**3 * jnp.cos(x)
    analytical_grad_y = 3 * y**2 * jnp.sin(x)
    
    print(f"Analytical Gradient for (x={x}, y={y}): ({analytical_grad_x}, {analytical_grad_y})")
    print(f"JAX Computed Gradient for (x={x}, y={y}): ({grad_x}, {grad_y})")
    print("---")


Analytical Gradient for (x=1.5, y=0.800000011920929): (3.036217451095581, 1.9151904582977295)
JAX Computed Gradient for (x=1.5, y=0.800000011920929): (3.036217451095581, 1.9151904582977295)
---
Analytical Gradient for (x=2.0, y=-1.2000000476837158): (4.719101905822754, 3.9281649589538574)
JAX Computed Gradient for (x=2.0, y=-1.2000000476837158): (4.719101905822754, 3.9281649589538574)
---
Analytical Gradient for (x=-0.5, y=2.5): (12.712226867675781, -8.989229202270508)
JAX Computed Gradient for (x=-0.5, y=2.5): (12.712226867675781, -8.989229202270508)
---


# Q6 sympy

In [65]:
import sympy as sp

# Define the symbols
x, y = sp.symbols('x y')

# Define the function
f = x**2 + y**3 * sp.sin(x)

# Calculate the gradient
gradient = [sp.diff(f, var) for var in (x, y)]

# Display the gradient
print("Gradient of f with respect to x and y:")
print(gradient)

Gradient of f with respect to x and y:
[2*x + y**3*cos(x), 3*y**2*sin(x)]


# Q7 Python nested dictionary

In [67]:
# Create a nested dictionary to represent the information
student_records = {
    2022: {
        'Branch 1': {
            'Roll Number': 1,
            'Name': 'N',
            'Marks': {
                'Maths': 100,
                'English': 70
                # Add more subjects and marks as needed
            }
        },
        'Branch 2': {
            # Add records for Branch 2 in 2022 if needed
        }
    },
    2023: {
        'Branch 1': {},
        'Branch 2': {}
        # Add records for 2023 as needed
    },
    2024: {
        'Branch 1': {},
        'Branch 2': {}
        # Add records for 2024 as needed
    },
    2025: {
        'Branch 1': {},
        'Branch 2': {}
        # Add records for 2025 as needed
    }
}

# Example: Accessing and updating records
student_records[2022]['Branch 1']['Marks']['History'] = 95  # Add History marks for Branch 1 in 2022
print(student_records[2022]['Branch 1'])  # Display records for Branch 1 in 2022

{'Roll Number': 1, 'Name': 'N', 'Marks': {'Maths': 100, 'English': 70, 'History': 95}}


# Q8 Using Python classes

In [68]:
class Student:
    def __init__(self, name, roll_number):
        self.name = name
        self.roll_number = roll_number
        self.marks = {}  # Dictionary to store subject-wise marks

class Branch:
    def __init__(self):
        self.students = []  # List to store Student objects

class Year:
    def __init__(self, year):
        self.year = year
        self.branches = []  # List to store Branch objects

    def add_branch(self, branch):
        self.branches.append(branch)

# Database (list of Year objects)
database = []

# Example data addition to the database
year_2022 = Year(2022)

branch_1_2022 = Branch()
student_1_2022 = Student('N', 1)
student_1_2022.marks['Maths'] = 100
student_1_2022.marks['English'] = 70
branch_1_2022.students.append(student_1_2022)

branch_2_2022 = Branch()

year_2022.add_branch(branch_1_2022)
year_2022.add_branch(branch_2_2022)

# Add year_2022 to the database
database.append(year_2022)

# Example: Accessing information
for year in database:
    print(f"Year: {year.year}")
    for branch in year.branches:
        print(f"Branch:")
        for student in branch.students:
            print(f"Name: {student.name}, Roll Number: {student.roll_number}, Marks: {student.marks}")

Year: 2022
Branch:
Name: N, Roll Number: 1, Marks: {'Maths': 100, 'English': 70}
Branch:


# Q10 Using Pandas For MATRIX

In [69]:
import numpy as np
import pandas as pd

# Generating the NumPy matrix
matrix = np.random.uniform(1, 2, size=(20, 5))

# Creating a DataFrame from the NumPy matrix with specified column names
df = pd.DataFrame(matrix, columns=['a', 'b', 'c', 'd', 'e'])

# Calculating standard deviations for each column
std_devs = df.std()

# Finding the column with the highest standard deviation
column_highest_std = std_devs.idxmax()
highest_std = std_devs.max()

print(f"Column '{column_highest_std}' has the highest standard deviation of {highest_std}")

# Calculating the mean for each row
row_means = df.mean(axis=1)

# Finding the row index with the lowest mean
row_lowest_mean_index = row_means.idxmin()
lowest_mean = row_means.min()

print(f"Row with index {row_lowest_mean_index} has the lowest mean of {lowest_mean}")

Column 'e' has the highest standard deviation of 0.3167000873757564
Row with index 17 has the lowest mean of 1.270254163819599


In [50]:
import numpy as np
import pandas as pd

# Generate a 20x5 matrix of random numbers between 1 and 2
matrix = np.random.uniform(1, 2, size=(20, 5))

# Create a Pandas DataFrame
df = pd.DataFrame(matrix, columns=['a', 'b', 'c', 'd', 'e'])

# Add a new column 'f' which is the sum of columns 'a', 'b', 'c', 'd', 'e'
df['f'] = df[['a', 'b', 'c', 'd', 'e']].sum(axis=1)

# Create column 'g' based on the value in column 'f'
df['g'] = np.where(df['f'] < 8, 'LT8', 'GT8')

# Find the number of rows where 'g' is 'LT8'
num_lt8_rows = df[df['g'] == 'LT8'].shape[0]

# Find the standard deviation of column 'f' for rows where 'g' is 'LT8' and 'GT8'
std_lt8 = df[df['g'] == 'LT8']['f'].std()
std_gt8 = df[df['g'] == 'GT8']['f'].std()

print("DataFrame with columns 'f' and 'g':")
print(df)
print("\nNumber of rows where 'g' is 'LT8':", num_lt8_rows)
print("Standard deviation of 'f' for 'LT8':", std_lt8)
print("Standard deviation of 'f' for 'GT8':", std_gt8)

DataFrame with columns 'f' and 'g':
           a         b         c         d         e         f    g
0   1.260401  1.410415  1.390195  1.911231  1.510742  7.482983  LT8
1   1.057573  1.625660  1.056924  1.239193  1.433884  6.413234  LT8
2   1.561453  1.797663  1.573422  1.963260  1.121540  8.017337  GT8
3   1.480881  1.062158  1.795668  1.171110  1.351508  6.861325  LT8
4   1.928208  1.314849  1.713793  1.165734  1.893864  8.016448  GT8
5   1.570833  1.436430  1.335015  1.056717  1.872803  7.271798  LT8
6   1.687015  1.354234  1.293559  1.158901  1.005102  6.498810  LT8
7   1.753380  1.257446  1.076365  1.472771  1.015259  6.575221  LT8
8   1.891214  1.964496  1.408553  1.825840  1.325460  8.415563  GT8
9   1.176897  1.210554  1.983465  1.515608  1.059212  6.945735  LT8
10  1.200199  1.806457  1.084171  1.955111  1.985099  8.031037  GT8
11  1.300996  1.462843  1.453288  1.259040  1.146736  6.622903  LT8
12  1.603481  1.216325  1.399441  1.638673  1.070844  6.928765  LT8
13  1.942686

# Q12 Broadcasting in numpy

Broadcasting in NumPy is a powerful concept that allows arithmetic operations to be performed on arrays of different shapes, enabling efficient computation without the need for explicitly creating arrays of the same shape.

In this example, x is a 2x3 array and y is a 1-dimensional array of length 3. Normally, you can't directly add arrays of different shapes. However, NumPy performs broadcasting in this case to make the operation possible.

Broadcasting operates on the smaller array (y) by "stretching" or "broadcasting" its shape to match the shape of the larger array (x). It duplicates the smaller array along the axis that is missing or has size 1 to match the shape of the larger array. Then, it performs the operation element-wise.

So, in the addition operation (x + y), y is effectively "broadcast" to match the shape of x by extending its shape to (2, 3) by repeating the rows. The addition is then performed element-wise, treating each element of y as if it were a row of the same shape as x.

This process of automatic alignment and stretching of arrays' shapes to perform element-wise operations efficiently is known as broadcasting in NumPy. It simplifies array operations, making code more concise and readable while maintaining efficient computation.

In [71]:
# Example arrays
x = np.array([[4, 7, 2], [1, 8, 3]])  # Shape: (2, 3)
y = np.array([15, 22, 37])           # Shape: (3,)

# Performing addition using broadcasting
result = x + y  # Broadcasting happens here

print("Array x:")
print(x)
print("\nArray y:")
print(y)
print("\nResult of x + y (Broadcasting):")
print(result)

Array x:
[[4 7 2]
 [1 8 3]]

Array y:
[15 22 37]

Result of x + y (Broadcasting):
[[19 29 39]
 [16 30 40]]


# Q13 argmin of a numpy array.

This function custom_argmin iterates through the array to find the minimum value and its index. It compares each element to the current minimum value and updates the minimum value and its index accordingly. We then compare the output of this custom function with np.argmin to verify its correctness. Both return the index of the minimum element in the array.

In [73]:
def custom_argmin(arr):
    # Initialize minimum value and index variables
    min_value = arr[0]  # Start with the first element
    min_index = 0

    # Iterate through the array to find the minimum value and its index
    for i, val in enumerate(arr):
        if val < min_value:
            min_value = val
            min_index = i

    return min_index

# Test the function
arr = np.array([5, 3, 8, 2, 6, 1])
argmin_custom = custom_argmin(arr)
argmin_numpy = np.argmin(arr)

print("Index of minimum element (Custom Function):", argmin_custom)
print("Index of minimum element (np.argmin):", argmin_numpy)


Index of minimum element (Custom Function): 5
Index of minimum element (np.argmin): 5
